services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspaces/app:cached
    command: sleep infinity
    depends_on:
      - postgres
      - minio
    networks:
      - saas-network

  postgres:
    image: postgres:15
    container_name: saas-kit-postgres
    restart: unless-stopped
    ports:
      # Expose to host; defaults to 5432 if DB_PORT is unset
      - "${DB_PORT:-5432}:5432"
    environment:
      # Defaults if .env is missing or incomplete
      POSTGRES_USER: "${DB_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
      POSTGRES_DB: "${DB_NAME:-saas_kit_db}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":8900"
    ports:
      - "9000:9000"
      - "8900:8900"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    volumes:
      - minio_data:/data
    networks:
      - saas-network

volumes:
  postgres_data:
  minio_data:

networks:
  saas-network:
    driver: bridge